{
	"version": 1545100540,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/punch-sheet0.png",
		"images/enemyred-sheet0.png",
		"images/enemyblue-sheet0.png",
		"images/breakableblock-sheet0.png",
		"images/springback.png",
		"images/tiledbackground.png",
		"images/springground.png",
		"images/springtiles.png",
		"images/coin-sheet0.png",
		"images/poof-sheet0.png",
		"images/waypoint-sheet0.png",
		"images/princess-sheet0.png",
		"images/princess-sheet1.png",
		"media/pickup_coin.m4a",
		"media/pickup_coin.ogg",
		"media/punch.m4a",
		"media/punch.ogg",
		"media/hit_hurt.m4a",
		"media/hit_hurt.ogg",
		"media/enemy_hurt.m4a",
		"media/enemy_hurt.ogg",
		"media/happy accident simple short loop.m4a",
		"media/happy accident simple short loop.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}